### ISSUE TITLE
Not compatible with ElasticSearch 2.x - "Wrong parameters for Exception"

### ISSUE THREAD

**Issue by CaredduMattia** [FriendsOfSymfony/FOSElasticaBundle#1000]
When i try to populate I get this error : 
```Error: Wrong parameters for Exception([string $exception [, long $code [, E  
  xception $previous = NULL]]])```

But with 1.7.4 all work rigth

**Comment by bdebon** [comment]
Same for me...

**Comment by piotrantosik** [comment]
Currently bundle does not support elastic in 2.x version, is require ```"ruflin/elastica": "~2.1",``` which is not compatible with this version - see https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/996 or https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/986

**Comment by merk** [comment]
As stated elsewhere, the jump to Elastica 3 causes a large number of test failures, if someone wanted to try to address the issues without breaking BC and send a PR we'd get support for ES2 quicker.

**Comment by TheFox** [comment]
Same here.

**Comment by oachoor** [comment]
Same for me,
elasticsearch --version : 2.1.1

**Comment by bobvandevijver** [comment]
This should be solved when this bundle upgrades the `composer.json` for `ruflin/elastica` to `~3.0` instead of `~2.1`. Not sure if it is that easy though.

**Comment by dario86** [comment]
Same error trying this query

```
'{  
    "query":{  
        "filtered":{  
            "filter":{  
                "bool":{  
                    "must":[  
                        {  
                            "geo_distance":{  
                                "distance":"200km",
                                "location":{  
                                    "lat":1000,
                                    "lon":999
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}'
```

**Comment by CaredduMattia** [comment]
Also updating the ruflin version to ~3.0 the problem is not solved.

**Comment by bechirsegni** [comment]
@oachoor same problem it doesn't work

**Comment by Gladhon** [comment]
With 3.1.1 it works look at #1014

**Comment by XWB** [comment]
Duplicate issue.
