### ISSUE TITLE
PopulateCommand - getLoggerClosure is gone

### ISSUE THREAD

**Issue by digitalkaoz** [FriendsOfSymfony/FOSElasticaBundle#817]
it appears that the function `getLoggerClosure` is gone, but still referenced in `Command/PopulateCommand.php:172`. What is the expected behavior?

**Comment by merk** [comment]
My fault with a bad merge. Fixed in 3.1-dev (i dont want to tag 3.1.0-RC2 just for this change)

**Comment by caramba1337** [comment]
seems to be still broken in 3.1-dev

"friendsofsymfony/elastica-bundle": "3.1.*@dev",

**Comment by merk** [comment]
Should be fixed
